-- MySQL Script generated by MySQL Workbench
-- Wed Jul  5 11:27:29 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';





CREATE SCHEMA IF NOT EXISTS `portfolio` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;

USE `portfolio` ;


CREATE TABLE IF NOT EXISTS `portfolio`.`type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb3;



CREATE TABLE IF NOT EXISTS `portfolio`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `age` VARCHAR(45) NOT NULL,
  `picture` VARCHAR(200) NOT NULL,
  `description` VARCHAR(2000) NOT NULL,
  `typeId` INT NOT NULL,
  `mail` VARCHAR(100) NOT NULL,
  `password` VARCHAR(200) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `role` INT NOT NULL,
  PRIMARY KEY (`id`, `typeId`),
  INDEX `fk_user_type1_idx` (`typeId` ASC) VISIBLE,
  CONSTRAINT `fk_user_type1`
    FOREIGN KEY (`typeId`)
    REFERENCES `portfolio`.`type` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb3;



CREATE TABLE IF NOT EXISTS `portfolio`.`project` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `theme` VARCHAR(45) NOT NULL,
  `description` VARCHAR(2000) NOT NULL,
  `userId` INT NOT NULL,
  `typeId` INT NOT NULL,
  `link` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`id`, `userId`, `typeId`),
  INDEX `fk_project_user_idx` (`userId` ASC) VISIBLE,
  INDEX `fk_project_type1_idx` (`typeId` ASC) VISIBLE,
  CONSTRAINT `fk_project_type1`
    FOREIGN KEY (`typeId`)
    REFERENCES `portfolio`.`type` (`id`),
  CONSTRAINT `fk_project_user`
    FOREIGN KEY (`userId`)
    REFERENCES `portfolio`.`user` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 22
DEFAULT CHARACTER SET = utf8mb3;


CREATE TABLE IF NOT EXISTS `portfolio`.`tech` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8mb3;



CREATE TABLE IF NOT EXISTS `portfolio`.`projecthastech` (
  `projectId` INT NOT NULL,
  `projectUserId` INT NOT NULL,
  `techId` INT NOT NULL,
  PRIMARY KEY (`projectId`, `projectUserId`, `techId`),
  INDEX `fk_project_has_tech_tech1_idx` (`techId` ASC) VISIBLE,
  INDEX `fk_project_has_tech_project1_idx` (`projectId` ASC, `projectUserId` ASC) VISIBLE,
  CONSTRAINT `fk_project_has_tech_tech1`
    FOREIGN KEY (`techId`)
    REFERENCES `portfolio`.`tech` (`id`),
  CONSTRAINT `projecthastech_ibfk_1`
    FOREIGN KEY (`projectId` , `projectUserId`)
    REFERENCES `portfolio`.`project` (`id` , `userId`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
